# Nombre del servicio actualizado
spring.application.name=attendance-service

# Configuracion JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Perfil activo por defecto
spring.profiles.active=local
# Personalizacion de la ruta de Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Paquete donde estan tus controladores (Adaptadores de Entrada)
springdoc.packages-to-scan=com.attendance.infrastructure.adapter.input.rest
